baseURL = 'https://ilexiv.github.io/GovTrade/'
languageCode = 'en-us'
title = 'Gov Trade'
theme = 'ananke'

[menu]
  [[menu.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menu.main]]
    name = 'About'
    pageRef = '/about'
    weight = 20
  [[menu.main]]
    name = 'Contact'
    pageRef = '/contact'
    weight = 30
